apiVersion: v1
kind: Service
metadata:
  labels:
    app: thinknyxdemo
  name: thinknyxdemosvc
  namespace: dhavishtest
spec:
  ports:
  - name: testsvc
   # nodePort: 30017
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: thinknyxdemo
  type: NodePort
